[2024-10-04T23:09:59.426+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_in_mysql.create_table_task manual__2024-10-04T23:09:51.768738+00:00 [queued]>
[2024-10-04T23:09:59.448+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_in_mysql.create_table_task manual__2024-10-04T23:09:51.768738+00:00 [queued]>
[2024-10-04T23:09:59.450+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-10-04T23:09:59.475+0000] {taskinstance.py:2191} INFO - Executing <Task(MySqlOperator): create_table_task> on 2024-10-04 23:09:51.768738+00:00
[2024-10-04T23:09:59.492+0000] {standard_task_runner.py:60} INFO - Started process 92 to run task
[2024-10-04T23:09:59.503+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'create_table_in_mysql', 'create_table_task', 'manual__2024-10-04T23:09:51.768738+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/mysql.py', '--cfg-path', '/tmp/tmpg9iw9uf0']
[2024-10-04T23:09:59.518+0000] {standard_task_runner.py:88} INFO - Job 128: Subtask create_table_task
[2024-10-04T23:09:59.734+0000] {task_command.py:423} INFO - Running <TaskInstance: create_table_in_mysql.create_table_task manual__2024-10-04T23:09:51.768738+00:00 [running]> on host ffa59a91c4ec
[2024-10-04T23:10:00.102+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_table_in_mysql' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T23:09:51.768738+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T23:09:51.768738+00:00'
[2024-10-04T23:10:00.108+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS clients (
            id INT AUTO_INCREMENT PRIMARY KEY,
            nom VARCHAR(100) NOT NULL,
            email VARCHAR(100) UNIQUE NOT NULL
        );
        
[2024-10-04T23:10:00.131+0000] {base.py:83} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2024-10-04T23:10:00.171+0000] {base.py:83} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2024-10-04T23:10:00.502+0000] {sql.py:450} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS clients (
            id INT AUTO_INCREMENT PRIMARY KEY,
            nom VARCHAR(100) NOT NULL,
            email VARCHAR(100) UNIQUE NOT NULL
        );
        , parameters: None
[2024-10-04T23:10:00.693+0000] {sql.py:459} INFO - Rows affected: 0
[2024-10-04T23:10:00.766+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=create_table_in_mysql, task_id=create_table_task, execution_date=20241004T230951, start_date=20241004T230959, end_date=20241004T231000
[2024-10-04T23:10:00.855+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-10-04T23:10:00.914+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
